config/routes.rb
BetaBanshee::Application.routes.draw do
  match '/contact', :to => 'pages#contact'
  match '/help',    :to => 'pages#help'

  root :to => 'pages#home'
  devise_for :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :encryptable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  #First try
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :authenticate_user!, :except => [:home, :contact]

  def home
    @title = "Home"
  end

  def contact
    @title = "Contacts"
  end

  def help
    @title = "Help"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Banshee"
    if @title.nil?
      base_title
    else
      "#{base_title} #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://bash.im/">Have a smile</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_forCss.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
</head>

app/views/layouts/_header.html.erb
<header>
  <% logo = image_tag("pict.png", :alt => "Banshee", :class => "round") %>
  <%= link_to logo, root_path %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= csrf_meta_tag %>
  <%= render 'layouts/forCss' %>
</head>
<body>
<div class="container">


  <div id="user_nav">
    <nav class="round">
    <% if user_signed_in? %>

        Signed in as <%= current_user.email %>. Not you?
        <%= link_to "Sign out", destroy_user_session_path %>
    <% else %>
        <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
    <% end %>
    </nav>
  </div>

  <%= render 'layouts/header' %>
    <section class="round">
    <%= yield %>
  </section>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/pages/contact.html.erb
<body>
    <h1> Contact Us: </h1>
    <p>
      <br> belotapo4kina@gmail.com </br>
      <br> pertsavigorstray@gmail.com </br>
    </p>
  </body>

app/views/pages/help.html.erb
 <body>
    <h1>All information you need</h1>
    <p>
      <br>
      <a href="http://beta-banshee.herokuapp.com/">Heroku Site </a>is our app
        released with <a href="http://www.heroku.com/">Heroku</a>.
      </br>
      <br>
        <a href="https://github.com/IgorPertsav/beta_banshee">Beta_banshee</a>
      </br>
      <br>
        This is fancy login IgorPertsav and pass 203Night20Spirit01 (special for O).
      </br>
      <br>
        This is a  good   <a href="http://railsapps.github.com/rails-heroku-tutorial.html">heroku tutorial</a>.
      </br>
      <br>
        This is some git tutorial <a href="http://progit.org/book/ru/ch2-5.html">tutorial 1</a> &
      <a href="http://progit.org/book/ru/ch5-4.html"> tutorial 2</a>
      </br>
    </p>
  </body>

app/views/pages/home.html.erb
<body>
    <h1> Home Page </h1>
        <p>
          This is home page for the our social network.
        </p>
    <%= link_to "Sign up now!", new_user_registration_path, :class => "signup_button round" %>
</body>